CREATE TABLE IF NOT EXISTS code_gen
(
    id          BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code_start  BIGINT    NOT NULL DEFAULT 0,
    code_end    BIGINT    NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS url_mapping
(
    id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    short_id    BIGINT      NOT NULL DEFAULT 0,
    url         VARCHAR(2000),          -- H2 没TEXT，改用大VARCHAR
    code        VARCHAR(45) NOT NULL DEFAULT '',
    hash        VARCHAR(90) NOT NULL DEFAULT '',
    status      TINYINT     NOT NULL DEFAULT 0,
    valid_start TIMESTAMP   NOT NULL DEFAULT '1970-01-01 00:00:00',
    valid_end   TIMESTAMP   NOT NULL DEFAULT '1970-01-01 00:00:00',
    create_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_url_hash_url (hash, url), -- H2不支持前缀索引，去掉长度限制
    UNIQUE uk_short_id (short_id),
    UNIQUE uk_code (code)
);

CREATE TABLE IF NOT EXISTS url_blocklist
(
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    block_id    BIGINT       NOT NULL DEFAULT 0,
    url         VARCHAR(2000),
    hash        VARCHAR(90)  NOT NULL DEFAULT '',
    remark      VARCHAR(255) NOT NULL DEFAULT '',
    status      TINYINT      NOT NULL DEFAULT 0,
    create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_blocklist_hash_url (hash, url),
    UNIQUE uk_block_id (block_id)
);

CREATE TABLE IF NOT EXISTS administrator
(
    id               BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    administrator_id BIGINT      NOT NULL DEFAULT 0,
    email            VARCHAR(90) NOT NULL DEFAULT '',
    username         VARCHAR(90) NOT NULL DEFAULT '',
    password         VARCHAR(90) NOT NULL DEFAULT '',
    create_time      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE uk_email (email),
    UNIQUE uk_administrator_id (administrator_id)
);
